clusterName: "dev-cluster"
location: "francecentral"
subscriptionID: "c5242457-78e0-4426-ad20-c44f0c26b7a9"
clientID: "0e504a0e-eec2-49f1-ad33-40e7135b9d15"
tenantID: "2f88d75e-5ed4-41c4-9556-e627fd1ee262"
authMode: "workloadidentity"
kubernetesVersion: v1.33.2
clusterNetwork: "overlay"
managedMachinePoolSpecs:
  pool0:
    count: 1
    enableAutoScaling: true
    enableEncryptionAtHost: false
    enableFIPS: false
    enableNodePublicIP: false
    enableUltraSSD: false
    maxCount: 3
    minCount: 1
    mode: System
    osSKU: AzureLinux
    vmSize: standard_d2s_v6
    type: VirtualMachineScaleSets
  pool1:
    count: 1
    enableAutoScaling: true
    enableEncryptionAtHost: false
    enableFIPS: false
    enableNodePublicIP: false
    enableUltraSSD: false
    maxCount: 3
    minCount: 1
    mode: User
    osSKU: AzureLinux
    vmSize: standard_d2s_v6
    type: VirtualMachineScaleSets
